---
- name: Create nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/nginx -t -q -c %s
  notify: restart nginx

- name: Create shanesofos.com Nginx site configuration
  template:
    src: sites-enabled-shanesofos.com.j2
    dest: /etc/nginx/sites-available/shanesofos.com
    owner: root
    group: root
    mode: 0644
  notify:
    - link shanesofos nginx conf
    - restart nginx
...
